### PR TITLE
Show flash messages

### PR DESCRIPTION
**Pull request by bryanjos**
connect #55

screen shot 2018-08-09 at 9 45 23 am

### CODE REVIEW

**Comment by lintomat** [comment]
To relint, [click here](http://lintron.prod.revelry.net/relint/revelrylabs/incentivize/108).

**Comment by brittanygay** [comment]
Hmm I might change the flash color so it doesn't match the primary color. Can I hop on your branch @bryanjos?

**Comment by bryanjos** [comment]
yes go for it

**Comment by lintomat** [comment]
To relint, [click here](http://lintron.prod.revelry.net/relint/revelrylabs/incentivize/108).

**Comment by brittanygay** [comment]
@bryanjos I just pushed up a styling update and changed out the success color. Here's a screenshot:

screen shot 2018-08-09 at 10 36 35 am

**Pull request merged**
