### PR TITLE
repository update/view screens

### PR DESCRIPTION
**Pull request by bryanjos**
connect #258 
connect #263 
connect #257 
connect #256 

#### Description:
- Screen for updating repositories
- Initial screen for updated view of project

screen shot 2018-10-02 at 1 21 28 pm

screen shot 2018-10-02 at 1 21 23 pm

screen shot 2018-10-02 at 8 16 36 pm

#### Reviewer don't-forgets:

- [ ] Test coverage feels appropriate, given potential risk
- [ ] We're not doubling down on already-bad code
- [ ] If there are web UI changes, they don't add anything that could be considered client-side page navigation (unless pre-approved as being necessary by another engineer)
- [ ] If there are web UI changes, they don't add any AJAX form submits (unless pre-approved as being necessary by another engineer)
- [ ] If there are any lint rules disabled, they are disabled per-line, and were (in the reviewer's judgment) appropriate to disable
- [ ] Any new environment variables used in the app are both documented and have been added to both staging and production environments already
- [ ] Potential race conditions are either inconsequential, or the code prevents them from occurring.
- [ ] If this is a UI change that called for screenshots/GIFs, in the reviewer's judgement, they were included

### CODE REVIEW

**Comment by lintomat** [comment]
To relint, [click here](http://lintron.prod.revelry.net/relint/revelrylabs/incentivize/292).

**Comment by lintomat** [comment]
To relint, [click here](http://lintron.prod.revelry.net/relint/revelrylabs/incentivize/292).

**Comment by lintomat** [comment]
To relint, [click here](http://lintron.prod.revelry.net/relint/revelrylabs/incentivize/292).

**Comment by lintomat** [comment]
To relint, [click here](http://lintron.prod.revelry.net/relint/revelrylabs/incentivize/292).

**Comment by lintomat** [comment]
To relint, [click here](http://lintron.prod.revelry.net/relint/revelrylabs/incentivize/292).

**Comment by brittanygay** [comment]
@bryanjos I just pushed up edits for the alignment fixes on the Repo Edit page, so this PR is now approved by me!

The demo screen looks good, but we should probably create a new ticket to clean that up/better the UX in the near future (like the rest of the screens).

Screenshots of updated Repo Edit screen:
screencapture-localhost-4000-repos-brittanygay-material-design-icons-edit-2018-10-03-16_55_45
screencapture-localhost-4000-repos-brittanygay-material-design-icons-edit-2018-10-03-16_58_25

**Pull request merged**
